const mongoose = require('mongoose');
const Joke = require('../models/joke');
require('dotenv').config();

// Connect to MongoDB
mongoose.connect(process.env.MONGO_URI);

const jokes = [
    {
        id: 21,
        question: 'What does a cloud wear under his raincoat?',
        encodedLetters: [
            {
                id: 1,
                letter: 'T',
                max: 16,
                min: 4,
                rightAnswer: false,
                sign: '*',
                total: 64,
            },
            {
                id: 2,
                letter: 'H',
                max: 24,
                min: 6,
                rightAnswer: false,
                sign: '/',
                total: 4,
            },
            {
                id: 3,
                letter: 'U',
                max: 15,
                min: 3,
                rightAnswer: false,
                sign: '*',
                total: 45,
            },
            {
                id: 4,
                letter: 'N',
                max: 40,
                min: 5,
                rightAnswer: false,
                sign: '/',
                total: 8,
            },
            {
                id: 5,
                letter: 'D',
                max: 14,
                min: 2,
                rightAnswer: false,
                sign: '*',
                total: 28,
            },
            {
                id: 6,
                letter: 'E',
                max: 42,
                min: 6,
                rightAnswer: false,
                sign: '/',
                total: 7,
            },
            {
                id: 7,
                letter: 'R',
                max: 18,
                min: 3,
                rightAnswer: false,
                sign: '*',
                total: 54,
            },
        ],
        difficulty: 'medium',
    },
    {
        id: 22,
        question: 'Why don’t some animals play cards in the jungle?',
        encodedLetters: [
            {
                id: 1,
                letter: 'T',
                max: 20,
                min: 5,
                rightAnswer: false,
                sign: '*',
                total: 100,
            },
            {
                id: 2,
                letter: 'O',
                max: 32,
                min: 8,
                rightAnswer: false,
                sign: '/',
                total: 4,
            },
            {
                id: 3,
                letter: 'O',
                max: 22,
                min: 2,
                rightAnswer: false,
                sign: '*',
                total: 44,
            },
            {
                id: 4,
                letter: 'M',
                max: 48,
                min: 6,
                rightAnswer: false,
                sign: '/',
                total: 8,
            },
            {
                id: 5,
                letter: 'A',
                max: 15,
                min: 3,
                rightAnswer: false,
                sign: '*',
                total: 45,
            },
            {
                id: 6,
                letter: 'N',
                max: 45,
                min: 5,
                rightAnswer: false,
                sign: '/',
                total: 9,
            },
            {
                id: 7,
                letter: 'Y',
                max: 18,
                min: 3,
                rightAnswer: false,
                sign: '*',
                total: 54,
            },
        ],
        difficulty: 'medium',
    },
    {
        id: 23,
        question: 'Why was the math book sad?',
        encodedLetters: [
            {
                id: 1,
                letter: 'T',
                max: 16,
                min: 2,
                rightAnswer: false,
                sign: '*',
                total: 32,
            },
            {
                id: 2,
                letter: 'O',
                max: 30,
                min: 6,
                rightAnswer: false,
                sign: '/',
                total: 5,
            },
            {
                id: 3,
                letter: 'O',
                max: 20,
                min: 4,
                rightAnswer: false,
                sign: '*',
                total: 80,
            },
            {
                id: 4,
                letter: 'M',
                max: 50,
                min: 10,
                rightAnswer: false,
                sign: '/',
                total: 5,
            },
            {
                id: 5,
                letter: 'A',
                max: 12,
                min: 3,
                rightAnswer: false,
                sign: '*',
                total: 36,
            },
            {
                id: 6,
                letter: 'N',
                max: 40,
                min: 8,
                rightAnswer: false,
                sign: '/',
                total: 5,
            },
            {
                id: 7,
                letter: 'Y',
                max: 15,
                min: 5,
                rightAnswer: false,
                sign: '*',
                total: 75,
            },
        ],
        difficulty: 'medium',
    },
    {
        id: 24,
        question: 'What do you call a pig that does karate?',
        encodedLetters: [
            {
                id: 1,
                letter: 'P',
                max: 10,
                min: 2,
                rightAnswer: false,
                sign: '*',
                total: 20,
            },
            {
                id: 2,
                letter: 'O',
                max: 24,
                min: 8,
                rightAnswer: false,
                sign: '/',
                total: 3,
            },
            {
                id: 3,
                letter: 'R',
                max: 15,
                min: 3,
                rightAnswer: false,
                sign: '*',
                total: 45,
            },
            {
                id: 4,
                letter: 'K',
                max: 32,
                min: 8,
                rightAnswer: false,
                sign: '/',
                total: 4,
            },
            {
                id: 5,
                letter: 'C',
                max: 12,
                min: 2,
                rightAnswer: false,
                sign: '*',
                total: 24,
            },
            {
                id: 6,
                letter: 'H',
                max: 36,
                min: 6,
                rightAnswer: false,
                sign: '/',
                total: 6,
            },
            {
                id: 7,
                letter: 'O',
                max: 10,
                min: 2,
                rightAnswer: false,
                sign: '*',
                total: 20,
            },
        ],
        difficulty: 'medium',
    },
    {
        id: 25,
        question: 'Why don’t we tell secrets on farms?',
        encodedLetters: [
            {
                id: 1,
                letter: 'C',
                max: 15,
                min: 3,
                rightAnswer: false,
                sign: '*',
                total: 45,
            },
            {
                id: 2,
                letter: 'O',
                max: 32,
                min: 8,
                rightAnswer: false,
                sign: '/',
                total: 4,
            },
            {
                id: 3,
                letter: 'R',
                max: 18,
                min: 6,
                rightAnswer: false,
                sign: '*',
                total: 108,
            },
            {
                id: 4,
                letter: 'N',
                max: 40,
                min: 10,
                rightAnswer: false,
                sign: '/',
                total: 4,
            },
            {
                id: 5,
                letter: 'Y',
                max: 12,
                min: 3,
                rightAnswer: false,
                sign: '*',
                total: 36,
            },
            {
                id: 6,
                letter: 'E',
                max: 48,
                min: 8,
                rightAnswer: false,
                sign: '/',
                total: 6,
            },
            {
                id: 7,
                letter: 'A',
                max: 15,
                min: 5,
                rightAnswer: false,
                sign: '*',
                total: 75,
            },
        ],
        difficulty: 'medium',
    }
]

// Insert the data into the database
Joke.insertMany(jokes)
    .then(() => {
        console.log('Data inserted successfully');
        mongoose.connection.close();
    })
    .catch((err) => {
        console.error(err);
        mongoose.connection.close();
    });
